development:
  adapter: postgresql
  database: sim_obras_sustentaveis
  host: localhost

test:
  adapter: postgresql
  database: sim_obras_sustentaveis_teste
  host: localhost

production:
  adapter: postgresql
  database: sim_obras_sustentaveis
  host: localhost