# encoding: UTF-8
# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema.define(version: 20130805200300) do

  create_table "admins", force: true do |t|
    t.string   "email",                  default: "",            null: false
    t.string   "encrypted_password",     default: "",            null: false
    t.string   "reset_password_token"
    t.datetime "reset_password_sent_at"
    t.datetime "remember_created_at"
    t.integer  "sign_in_count",          default: 0
    t.datetime "current_sign_in_at"
    t.datetime "last_sign_in_at"
    t.string   "current_sign_in_ip"
    t.string   "last_sign_in_ip"
    t.datetime "created_at",                                     null: false
    t.datetime "updated_at",                                     null: false
    t.string   "name"
    t.string   "role",                   default: "pesquisador"
  end

  add_index "admins", ["email"], name: "index_admins_on_email", unique: true, using: :btree
  add_index "admins", ["reset_password_token"], name: "index_admins_on_reset_password_token", unique: true, using: :btree

  create_table "constructions", force: true do |t|
    t.datetime "created_at",                                                      null: false
    t.datetime "updated_at",                                                      null: false
    t.string   "codigo_obra"
    t.string   "nome_da_obra"
    t.string   "tipo_de_logradouro"
    t.string   "logradouro"
    t.string   "bairro"
    t.string   "cep"
    t.string   "estado"
    t.string   "cidade"
    t.string   "m2_unidade"
    t.string   "m2_util_total"
    t.string   "numero_de_andares"
    t.string   "projeto"
    t.string   "lancamento"
    t.string   "fundacao"
    t.string   "estrutura"
    t.string   "acabamento"
    t.string   "paralisada"
    t.string   "concluida"
    t.string   "proprietario1"
    t.string   "proprierario2"
    t.string   "proprietario3"
    t.string   "proprietario4"
    t.string   "investidor1"
    t.string   "investidor2"
    t.string   "investidor3"
    t.string   "investidor4"
    t.string   "construtora1_codigo"
    t.string   "construtora2_codigo"
    t.string   "construtora3_codigo"
    t.string   "construtora4_codigo"
    t.string   "tipo_de_obra"
    t.string   "tipo_de_obra_outros"
    t.text     "ficha_tecnica_observacao"
    t.boolean  "sistema_leed"
    t.boolean  "sistema_aqua"
    t.boolean  "sistema_procel_edifica"
    t.boolean  "sistema_qualiverde"
    t.boolean  "sistema_bream"
    t.boolean  "sistema_dgnb"
    t.boolean  "sistema_lbc"
    t.string   "sistema_outros"
    t.boolean  "leed_nc"
    t.boolean  "leed_cs"
    t.boolean  "leed_ci"
    t.boolean  "leed_eb"
    t.boolean  "aqua_bairros"
    t.boolean  "aqua_edificios"
    t.boolean  "aqua_servicos"
    t.boolean  "aqua_operacao_e_uso"
    t.boolean  "procel_residencial"
    t.boolean  "procel_comercial"
    t.string   "tipo_de_sistema_outros"
    t.string   "versao_do_sistema"
    t.string   "leed_platinum"
    t.string   "leed_gold"
    t.string   "leed_silver"
    t.string   "leed_certified"
    t.string   "perfil_nivel_de_certificacao"
    t.boolean  "vagas_verdes"
    t.integer  "vagas_verdes_quantidade"
    t.boolean  "estacoes_de_recarga_de_veiculos_eletricos"
    t.integer  "estacoes_de_recarga_de_veiculos_eletricos_quantidade"
    t.boolean  "bicicletarios"
    t.integer  "bicicletarios_quantidade"
    t.boolean  "vestiarios_com_chuveiro"
    t.integer  "vestiarios_com_chuveiro_quantidade"
    t.boolean  "proximidade_ao_tpublico_metro"
    t.integer  "proximidade_ao_tpublico_metro_distancia_aproximada"
    t.boolean  "proximidade_ao_tpublico_trem"
    t.string   "proximidade_ao_tpublico_trem_distancia_aproximada"
    t.boolean  "proximidade_ao_tpublico_ponto_de_onibus"
    t.string   "proximidade_ao_tpublico_ponto_de_onibus_distancia_aproximada"
    t.string   "proximidade_ao_tpublico_outros"
    t.string   "proximidade_ao_tpublico_outros_distancia_aproximada"
    t.boolean  "reducao_do_efeito_de_ilhas_de_calor_alta_refletância_solar"
    t.boolean  "reducao_do_efeito_de_ilhas_de_calor_telhado_verde"
    t.string   "reducao_do_efeito_de_ilhas_de_calor__outros"
    t.boolean  "bacias_e_mictorios_bacias_a_vacuo"
    t.boolean  "bacias_e_mictorios_bacias_dual_flux"
    t.boolean  "bacias_e_mictorios_het"
    t.boolean  "bacias_e_mictorios_mictorios_secos"
    t.boolean  "bacias_e_mictorios_mictorio_eficiente"
    t.boolean  "bacias_e_mictorios_mictorio_fechamento_hidromecanico"
    t.boolean  "bacias_e_mictorios_mictorio_fechamento_com_sensor_de_presenca"
    t.string   "outros"
    t.string   "torneiras"
    t.string   "chuveiros"
    t.string   "irrigacao"
    t.string   "piscina"
    t.boolean  "torres_de_resfriamento"
    t.string   "torres_de_resfriamento_tipo"
    t.boolean  "agua_pluvial"
    t.boolean  "agua_pluvial_para_irrigacao_do_paisagismo"
    t.boolean  "agua_pluvial_para_lavagem_de_pisos"
    t.boolean  "agua_pluvial_para_bacias"
    t.boolean  "agua_pluvial_para_ar_condicionado"
    t.boolean  "agua_pluvial_piscina"
    t.string   "agua_pluvial_outros"
    t.boolean  "agua_de_lencol"
    t.boolean  "agua_de_lencol_para_irrigacao_do_paisagismo"
    t.boolean  "agua_de_lencol_para_lavagem_de_pisos"
    t.boolean  "agua_de_lencol_para_bacias"
    t.boolean  "agua_de_lencol_para_ar_condicionado"
    t.boolean  "agua_de_lencol_piscina"
    t.string   "agua_de_lencol_outros"
    t.boolean  "agua_condensacao_tratada"
    t.boolean  "agua_condensacao_tratada_para_irrigacao_do_paisagismo"
    t.boolean  "agua_condensacao_tratada_para_lavagem_de_pisos"
    t.boolean  "agua_condensacao_tratada_para_bacias"
    t.boolean  "agua_condensacao_tratada_para_ar_condicionado"
    t.boolean  "agua_condensacao_tratada_piscina"
    t.string   "agua_condensacao_tratada_outros"
    t.boolean  "agua_cinza_tratada"
    t.boolean  "agua_cinza_tratada_para_irrigacao_do_paisagismo"
    t.boolean  "agua_cinza_tratada_para_lavagem_de_pisos"
    t.boolean  "agua_cinza_tratada_para_bacias"
    t.boolean  "agua_cinza_tratada_para_ar_condicionado"
    t.boolean  "agua_cinza_tratada_piscina"
    t.string   "agua_cinza_tratada_outros"
    t.boolean  "agua_negra_tratada"
    t.boolean  "agua_negra_tratada_para_irrigacao_do_paisagismo"
    t.boolean  "agua_negra_tratada_para_lavagem_de_pisos"
    t.boolean  "agua_negra_tratada_para_bacias"
    t.boolean  "agua_negra_tratada_para_ar_condicionado"
    t.boolean  "agua_negra_tratada_piscina"
    t.string   "agua_negra_tratada_outros"
    t.boolean  "drenagem_pisos_permeaveis"
    t.boolean  "drenagem_caixa_de_retardo"
    t.boolean  "drenagem_remocao_de_solidos_suspensos"
    t.string   "drenagem_outros"
    t.boolean  "vrf"
    t.string   "vrf_tipo"
    t.boolean  "central_de_agua_gelada"
    t.string   "central_de_agua_gelada_tipo"
    t.string   "ar_condicionado_outros"
    t.string   "tratamento_de_ar_externo_outros"
    t.boolean  "variador_frequencia_nos_ventiladores_de_tomadas_de_ar_externos"
    t.boolean  "variador_frequencia_nos_fan_coils"
    t.boolean  "variador_frequencia_nos_chillers"
    t.string   "variador_frequencia_outros"
    t.boolean  "tipo_de_insuflamento_de_ar"
    t.boolean  "tipo_de_insuflamento_de_ar_teto"
    t.boolean  "tipo_de_insuflamento_de_ar_piso"
    t.boolean  "tipo_de_insuflamento_de_ar_vigas_frias"
    t.string   "tipo_de_insuflamento_de_ar_teto_outros"
    t.string   "tipos_de_protecoes_solares"
    t.boolean  "vidros_area_envidracada"
    t.boolean  "vidros_area_envidracada_laminado"
    t.boolean  "vidros_area_envidracada_low_e"
    t.boolean  "vidros_area_envidracada_da_fachada"
    t.string   "vidros_area_envidracada_da_fachada_porcentagem"
    t.boolean  "eletrica_motor_de_alta_eficiencia"
    t.boolean  "eletrica_medicao_setorizada_de_consumo_de_energia"
    t.boolean  "eletrica_entrada_de_energia"
    t.string   "eletrica_tipo"
    t.boolean  "eletrica_fonte_de_energia"
    t.boolean  "eletrica_fonte_de_energia_eletrica"
    t.boolean  "eletrica_fonte_de_energia_gas"
    t.string   "eletrica_fonte_de_energia_outros"
    t.boolean  "energia_alternativa_solar_fotovoltaica"
    t.boolean  "energia_alternativa_aquecimento_solar_de_agua"
    t.boolean  "energia_alternativa_eolica"
    t.boolean  "energia_alternativa_biomassa"
    t.string   "energia_alternativa_outros"
    t.boolean  "iluminacao_lampadas_t5"
    t.boolean  "iluminacao_lampadas_t5_area_privativa"
    t.boolean  "iluminacao_lampadas_t5_area_comum"
    t.boolean  "iluminacao_lampadas_led"
    t.boolean  "iluminacao_integracao_da_iluminacao_com_a_iluminacao_natural"
    t.boolean  "iluminacao_dali"
    t.boolean  "iluminacao_sensores_de_presenca_em_areas_comuns"
    t.boolean  "iluminacao_controles_acionamento_automatizado"
    t.boolean  "iluminacao_fotocelulas_na_iluminacao_externa"
    t.string   "iluminacao_outros"
    t.boolean  "equipamentos_elevadores_eficientes"
    t.boolean  "equipamentos_frenagem_regenerativa"
    t.boolean  "equipamentos_adc"
    t.string   "equipamentos_outros"
    t.string   "material_de_baixo_voc"
    t.string   "material_de_baixo_voc_outros"
    t.string   "madeira_certificada"
    t.string   "pisos_e_carpetes_certificados"
    t.boolean  "coleta_de_residuos_reciclaveis_deposito_central"
    t.boolean  "coleta_de_residuos_reciclaveis_deposito_no_pavimento"
    t.string   "coleta_de_residuos_reciclaveis_outros"
    t.boolean  "nivel_de_filtragem"
    t.string   "nivel_de_filtragem_nivel"
    t.boolean  "sistemas_de_tratamento_de_ar_interno"
    t.string   "sistemas_de_tratamento_de_ar_interno_outros"
    t.date     "inicio_da_obra"
    t.date     "termino_da_obra"
    t.string   "construtora1_razao_social"
    t.string   "construtora2_razao_social"
    t.string   "construtora3_razao_social"
    t.string   "construtora4_razao_social"
    t.boolean  "agua_de_condensacao"
    t.boolean  "agua_condensacao"
    t.boolean  "tratamento_de_ar_externo_roda_entalpica"
    t.boolean  "tratamento_de_ar_externo_trocador_de_calor"
    t.boolean  "vidros_area_envidracada_insulado"
    t.string   "como_esta_reduzindo_ilhas_de_calor"
    t.boolean  "como_esta_reduzindo_ilhas_de_calor_alta_refletancia"
    t.boolean  "como_esta_reduzindo_ilhas_de_calor_telhado_verde"
    t.string   "como_esta_reduzindo_ilhas_de_calor_outros"
    t.string   "tipo_de_insuflamento_de_ar_outros"
    t.string   "vidros_area_envidracada_outros"
    t.boolean  "coleta_de_residuos_reciclaveis_nivel_de_filtragem"
    t.string   "coleta_de_residuos_reciclaveis_nivel_de_filtragem_tipo"
    t.string   "coleta_de_residuos_reciclaveis_sistema_trat_ar_interno"
    t.string   "sist_trat_ar_interno"
    t.string   "coleta_de_residuos_reciclaveis_nivel_filtragem"
    t.boolean  "teve_consultoria"
    t.string   "teve_consultoria_qual_empresa"
    t.string   "contato1_nome"
    t.string   "contato1_telefone"
    t.string   "contato1_email"
    t.string   "contato2_nome"
    t.string   "contato2_telefone"
    t.string   "contato2_email"
    t.string   "contato3_nome"
    t.string   "contato3_telefone"
    t.string   "contato3_email"
    t.string   "contato4_nome"
    t.string   "contato4_telefone"
    t.string   "contato4_email"
    t.string   "contato5_nome"
    t.string   "contato5_telefone"
    t.string   "contato5_email"
    t.string   "contato1_razao_social"
    t.string   "contato2_razao_social"
    t.string   "contato3_razao_social"
    t.string   "contato4_razao_social"
    t.string   "contato5_razao_social"
    t.string   "contato1_funcao"
    t.string   "contato2_funcao"
    t.string   "contato3_funcao"
    t.string   "contato4_funcao"
    t.string   "contato5_funcao"
    t.string   "numero_de_unidades"
    t.string   "estrutura_utilizada"
    t.string   "laje_utilizada"
    t.boolean  "como_esta_reduzindo_ilhas_de_calor_vagas_cobertas"
    t.boolean  "como_esta_reduzindo_ilhas_de_calor_piso_concregama"
    t.boolean  "torneiras_restritores_de_vazao"
    t.boolean  "torneiras_acionamento_hidromecanico"
    t.boolean  "torneiras_sensor_de_presenca"
    t.boolean  "torneiras_regulador_de_vazao"
    t.boolean  "torneiras_outros_enable"
    t.string   "torneiras_outros"
    t.string   "torres_de_resfriamento_tipo_especifico"
    t.boolean  "agua_pluvial_para_bacias_e_mictorios"
    t.string   "medicao_de_agua"
    t.string   "perfil_nivel_de_certificacao_outros"
    t.string   "medicao_setorizada_de_consumos"
    t.string   "medicao_de_agua_outros"
    t.string   "drenagem_captacao_e_aproveitamente_de_agua_pluvial"
    t.string   "ar_condicionado"
    t.string   "ar_condicionado_condensacao"
    t.string   "ar_condicionado_condensacao_outros"
    t.string   "equipamentos"
    t.string   "variadores_de_frequencia"
    t.string   "variadores_de_frequencia_outros"
    t.string   "tratamento_de_ar_externo_controle_de_demanda_de_ventilacao_por_"
    t.string   "existe_area_envidracada_na_fachada"
    t.string   "insulado"
    t.string   "laminado"
    t.string   "low_e_baixa_emissividade"
    t.string   "eletrica_tamanho_da_entrada_tipo_de_fonte_de_energia"
    t.string   "entrada_de_energia"
    t.string   "eletrica"
    t.string   "gas"
    t.string   "peak_shaving"
    t.string   "possui_100_de_backup"
    t.string   "eletrica_tamanho_da_entrada_tipo_de_fonte_de_energia_outros"
    t.string   "medicao_de_energia"
    t.string   "elevadores"
    t.string   "ventilacao"
    t.string   "iluminacao"
    t.string   "outros_caixa_de_texto"
    t.string   "torres_de_resfriamento_sim"
    t.string   "ar_condicionado_condensacao_vrf"
    t.string   "ar_condicionado_condensacao_central_de_agua_gelada"
    t.string   "perfil_nivel_de_certificacao_enable_categoria_n_1_relacao_do_"
    t.string   "ar_condicionado_condensacao_bom"
  end

  create_table "logs", force: true do |t|
    t.integer  "admin_id"
    t.string   "action"
    t.string   "details"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

end
